spring:
  application:
    name: service-user
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.92.129:8848
      config:
        server-addr: 192.168.92.129:8848
        file-extension: yaml
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml
      - nacos:common.yaml